security:
    enable_authenticator_manager: true

#    access_decision_manager:
#        strategy: unanimous

    encoders:
        App\Security\AppUser: 'plaintext'
    providers:
        app_users:
            id: App\Security\AppUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: .*
            # REMOVE ANONYMOUS WHEN enable_authenticator_manage=true
#            anonymous: true
            lazy: false
            provider: app_users
            logout:
                path: api_logout
                invalidate_session: true
                success_handler: App\Security\LogoutSuccessHandler
            two_factor:
                auth_form_path: api_2fa_login
                check_path: api_2fa_check
                prepare_on_login: true
                prepare_on_access_denied: true
                authentication_required_handler: App\Security\TwoFactorRequiredHandler
                success_handler: App\Security\TwoFactorSuccessHandler
                failure_handler: App\Security\TwoFactorFailureHandler
            json_login:
                check_path: api_login
                success_handler: App\Security\LoginSuccessHandler

    access_control:
        - { path: '^/logout', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/2fa', roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: '^/protected', roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/', roles: IS_AUTHENTICATED_ANONYMOUSLY }
